// SPDX-License-Identifier: Apache-2.0

//! Confined, staged generation: plan validation, rendering, provenance,
//! the state manifest, orphans, ownership, and delivery.

mod common;

use bearout::{Code, Mode};
use common::{Project, assert_clean, assert_line, codes};

const TEMPLATE: &str =
    "{% for line in bearout.header %}<!-- {{ line }} -->\n{% endfor %}\n# {{ title }}\n";

fn gen_project(plan: &str) -> Project {
    let project = Project::with_note();
    project.file("bearout.toml", common::BOOTSTRAP_GEN);
    project.file("templates/page.md.j2", TEMPLATE);
    project.file("templates/data.json.j2", "{{ title | tojson }}\n");
    project.file(
        common::ENTRY,
        &format!("def g(p):\n    return [{plan}]\nschema(\"example/test/note@1\", shape = \"note.schema.toml\")\ngenerator(\"pages\", g)\n"),
    );
    project
}

#[test]
fn writes_verifies_and_records_provenance() {
    let project = gen_project(
        "output(\"page.md.j2\", \"generated/a.md\", context = {\"title\": \"A\"}), output(\"data.json.j2\", \"generated/a.json\", context = {\"title\": \"A\"})",
    );
    let report = project.generate(Mode::Check);
    assert_line(&report, "generated/a.md:B020: generated file is missing");
    assert_line(
        &report,
        "bearout-state.toml:B020: state manifest is missing",
    );

    let report = project.generate(Mode::Write);
    assert_clean(&report);
    assert_eq!(report.outputs, ["generated/a.json", "generated/a.md"]);
    let page = project.read("generated/a.md");
    assert!(
        page.starts_with(
            "<!-- SPDX-License-Identifier: Apache-2.0 -->\n<!-- Generated by Bearout "
        )
    );
    assert!(page.contains("generator `pages`, template `page.md.j2`"));
    assert_eq!(project.read("generated/a.json"), "\"A\"\n");
    let state = project.read("bearout-state.toml");
    assert!(state.contains("path = \"generated/a.md\""));
    assert!(state.contains("digest = \"blake3:"));
    assert!(state.contains("inputs = \"blake3:"));

    assert_clean(&project.generate(Mode::Check));
    let again = project.generate(Mode::Write);
    assert_clean(&again);
    assert_eq!(project.read("bearout-state.toml"), state);
}

#[test]
fn stale_orphaned_and_reowned_outputs_are_reported() {
    let project =
        gen_project("output(\"page.md.j2\", \"generated/a.md\", context = {\"title\": \"A\"})");
    assert_clean(&project.generate(Mode::Write));

    project.file("generated/a.md", "edited\n");
    assert_line(
        &project.generate(Mode::Check),
        "generated/a.md:B020: generated file is stale",
    );
    assert_clean(&project.generate(Mode::Write));

    project.file(common::ENTRY, "def g(p):\n    return [output(\"page.md.j2\", \"generated/b.md\", context = {\"title\": \"B\"})]\nschema(\"example/test/note@1\", shape = \"note.schema.toml\")\ngenerator(\"pages\", g)\n");
    let report = project.generate(Mode::Check);
    assert_line(&report, "generated/a.md:B020: orphaned output");
    assert_line(&report, "generated/b.md:B020: generated file is missing");
    let report = project.generate(Mode::Write);
    assert_clean(&report);
    assert!(
        !project.exists("generated/a.md"),
        "owned, unmodified orphans are removed"
    );
    assert!(project.exists("generated/b.md"));

    project.file(common::ENTRY, "def g(p):\n    return [output(\"page.md.j2\", \"generated/b.md\", context = {\"title\": \"B\"})]\nschema(\"example/test/note@1\", shape = \"note.schema.toml\")\ngenerator(\"other\", g)\n");
    assert_line(
        &project.generate(Mode::Check),
        "generated/b.md:B020: ownership changed: previously generator `pages`",
    );
}

#[test]
fn modified_orphans_and_unowned_files_are_never_touched() {
    let project =
        gen_project("output(\"page.md.j2\", \"generated/a.md\", context = {\"title\": \"A\"})");
    assert_clean(&project.generate(Mode::Write));
    project.file("generated/a.md", "hand edited after generation\n");
    project.file(common::ENTRY, "def g(p):\n    return []\nschema(\"example/test/note@1\", shape = \"note.schema.toml\")\ngenerator(\"pages\", g)\n");
    let report = project.generate(Mode::Write);
    assert_line(
        &report,
        "generated/a.md:B020: orphaned output was modified after Bearout wrote it; not removed",
    );
    assert_eq!(
        project.read("generated/a.md"),
        "hand edited after generation\n"
    );

    let project =
        gen_project("output(\"page.md.j2\", \"generated/a.md\", context = {\"title\": \"A\"})");
    project.file("generated/a.md", "someone else's file\n");
    let report = project.generate(Mode::Write);
    assert_line(
        &report,
        "generated/a.md:B021: refusing to overwrite a file the state manifest does not own",
    );
    assert_eq!(project.read("generated/a.md"), "someone else's file\n");
    assert!(!project.exists("bearout-state.toml"));
}

#[test]
fn plans_are_confined_and_collision_free() {
    let cases = [
        ("output(\"page.md.j2\", \"../escape.md\")", "output path"),
        ("output(\"page.md.j2\", \"/etc/x.md\")", "output path"),
        (
            "output(\"page.md.j2\", \"content/x.md\")",
            "is not beneath a declared output root",
        ),
        (
            "output(\"page.md.j2\", \"generated\")",
            "is not beneath a declared output root",
        ),
        (
            "output(\"page.md.j2\", \"generated/x.md\"), output(\"page.md.j2\", \"generated/X.md\")",
            "collides with `generated/x.md`",
        ),
        (
            "output(\"page.md.j2\", \"generated\\\\x.md\"), output(\"page.md.j2\", \"generated/x.md\")",
            "backslashes are not path separators",
        ),
        (
            "output(\"../page.md.j2\", \"generated/x.md\")",
            "output template",
        ),
        (
            "output(\"missing.j2\", \"generated/x.md\")",
            "template `missing.j2` does not exist beneath the templates root",
        ),
        (
            "output(\"page.md.j2\", \"generated/x.md\", context = 3)",
            "output context must be a dict",
        ),
        (
            "output(\"page.md.j2\", \"generated/x.md\", context = {\"title\": \"A\", \"oops\": \"x\"})",
            "generated/x.md",
        ),
    ];
    for (plan, expected) in cases {
        let project = gen_project(plan);
        let report = project.generate(Mode::Write);
        assert!(
            !project.exists("generated/x.md") || expected == "generated/x.md",
            "{plan}"
        );
        if expected != "generated/x.md" {
            assert_line(&report, expected);
            assert!(
                codes(&report).iter().all(|c| matches!(
                    c,
                    Code::PlanInvalid | Code::ScriptFailure | Code::ScriptLoad | Code::ScriptResult
                )),
                "{plan}: {:?}",
                codes(&report)
            );
        }
    }
}

#[test]
fn strict_templates_and_provenance_headers() {
    let project = gen_project("output(\"page.md.j2\", \"generated/x.md\", context = {})");
    let report = project.generate(Mode::Write);
    assert_line(&report, "template `page.md.j2`");
    assert!(codes(&report).contains(&Code::PlanInvalid));

    let project = gen_project("output(\"bare.md.j2\", \"generated/x.md\", context = {})");
    project.file("templates/bare.md.j2", "# no header\n");
    assert_line(
        &project.generate(Mode::Write),
        "must carry the provenance header",
    );

    let project = gen_project("output(\"nolic.md.j2\", \"generated/x.md\", context = {})");
    project.file(
        "templates/nolic.md.j2",
        "<!-- Generated by Bearout by hand -->\n# no spdx\n",
    );
    assert_line(&project.generate(Mode::Write), "must carry the SPDX header");
}

#[cfg(unix)]
#[test]
fn outputs_are_never_written_through_symlinks() {
    let outside = tempfile::tempdir().expect("outside");
    let project = gen_project(
        "output(\"page.md.j2\", \"generated/link/a.md\", context = {\"title\": \"A\"})",
    );
    std::fs::create_dir_all(project.path().join("generated")).expect("dir");
    std::os::unix::fs::symlink(outside.path(), project.path().join("generated/link"))
        .expect("symlink");
    let report = project.generate(Mode::Write);
    assert_line(
        &report,
        "generated/link/a.md:B021: `generated/link` is a symbolic link",
    );
    assert!(!outside.path().join("a.md").exists());
}

#[test]
fn generation_without_templates_root_is_a_diagnostic() {
    let project =
        gen_project("output(\"page.md.j2\", \"generated/a.md\", context = {\"title\": \"A\"})");
    project.file(
        "bearout.toml",
        &common::BOOTSTRAP_GEN.replace("[templates]\nroot = \"templates\"\n", ""),
    );
    assert_line(
        &project.generate(Mode::Write),
        "bearout.toml:B019: generators need a `[templates]` root",
    );
    project.file("bearout.toml", common::BOOTSTRAP);
    assert_line(
        &project.generate(Mode::Write),
        "is not beneath a declared output root",
    );
}

#[test]
fn outputs_are_delivered_in_stable_order_and_nested_directories_are_created() {
    let project = gen_project(
        "output(\"page.md.j2\", \"generated/z/deep/z.md\", context = {\"title\": \"Z\"}), output(\"page.md.j2\", \"generated/a.md\", context = {\"title\": \"A\"})",
    );
    let report = project.generate(Mode::Write);
    assert_clean(&report);
    assert_eq!(report.outputs, ["generated/a.md", "generated/z/deep/z.md"]);
    let state = project.read("bearout-state.toml");
    assert!(state.find("generated/a.md") < state.find("generated/z/deep/z.md"));
}
