// SPDX-License-Identifier: Apache-2.0
// Generated by Bearout 0.1.0: generator `formulo-crate`, template `conformance.rs.j2`. Do not edit.

//! Conformance corpus: one test per example resource.

use formulo::parser::{ErrorKind, parse};

/// `IF` accepts at most three arguments.
#[test]
fn example_arity_high() {
    let error = parse("=IF(1, 2, 3, 4)").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::WrongArgumentCount);
}

/// `IF` needs at least two arguments.
#[test]
fn example_arity_low() {
    let error = parse("=IF(1)").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::WrongArgumentCount);
}

/// Subtraction is left associative.
#[test]
fn example_associativity() {
    let expr = parse("=8 - 3 - 2").expect("example parses");
    assert_eq!(
        expr.to_string(),
        "(binary subtract (binary subtract (number 8) (number 3)) (number 2))"
    );
}

/// A bare identifier is not an expression.
#[test]
fn example_bare_identifier() {
    let error = parse("=total").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::UnexpectedToken);
}

/// Keywords are case-insensitive; the second `=` is the comparison operator.
#[test]
fn example_booleans() {
    let expr = parse("=true = FALSE").expect("example parses");
    assert_eq!(expr.to_string(), "(binary equal (bool true) (bool false))");
}

/// Column letters are normalized to upper case; `$` marks absolute parts.
#[test]
fn example_cells() {
    let expr = parse("=$a$1 + b2").expect("example parses");
    assert_eq!(expr.to_string(), "(binary add (cell $A$1) (cell B2))");
}

/// Comparisons are left associative.
#[test]
fn example_comparison_chain() {
    let expr = parse("=1 < 2 <> 3").expect("example parses");
    assert_eq!(
        expr.to_string(),
        "(binary not-equal (binary less (number 1) (number 2)) (number 3))"
    );
}

/// A literal needs a leading digit. `.5` starts no token, so the lexer stops at `.` with an invalid character.
#[test]
fn example_decimal() {
    let error = parse("=1.50 + .5").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::InvalidCharacter);
}

/// Empty input has no leading `=`.
#[test]
fn example_empty() {
    let error = parse("").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::MissingLeadingEquals);
}

/// Parentheses override precedence.
#[test]
fn example_grouping() {
    let expr = parse("=(1 + 2) * 3").expect("example parses");
    assert_eq!(
        expr.to_string(),
        "(binary multiply (binary add (number 1) (number 2)) (number 3))"
    );
}

/// `#` starts no token.
#[test]
fn example_invalid_character() {
    let error = parse("=1 # 2").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::InvalidCharacter);
}

/// A formula must begin with `=`.
#[test]
fn example_missing_equals() {
    let error = parse("1 + 2").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::MissingLeadingEquals);
}

/// Calls nest and take expressions as arguments.
#[test]
fn example_nested_calls() {
    let expr = parse("=IF(A1 > 0, MAX(A1, 1), MIN(A1, -1))").expect("example parses");
    assert_eq!(
        expr.to_string(),
        "(call IF (binary greater (cell A1) (number 0)) (call MAX (cell A1) (number 1)) (call MIN (cell A1) (unary negate (number 1))))"
    );
}

/// Exponentiation is right associative.
#[test]
fn example_power_right() {
    let expr = parse("=2^3^2").expect("example parses");
    assert_eq!(
        expr.to_string(),
        "(binary power (number 2) (binary power (number 3) (number 2)))"
    );
}

/// Multiplication binds tighter than addition.
#[test]
fn example_precedence() {
    let expr = parse("=1 + 2 * 3").expect("example parses");
    assert_eq!(
        expr.to_string(),
        "(binary add (number 1) (binary multiply (number 2) (number 3)))"
    );
}

/// A range argument.
#[test]
fn example_range() {
    let expr = parse("=SUM(A1:B3)").expect("example parses");
    assert_eq!(expr.to_string(), "(call SUM (range A1 B3))");
}

/// Doubled quotes inside a string stand for one quote.
#[test]
fn example_string_escape() {
    let expr = parse("=\"say \"\"hi\"\"\"").expect("example parses");
    assert_eq!(expr.to_string(), "(string \"say \\\"hi\\\"\")");
}

/// Input after a complete formula is an error.
#[test]
fn example_trailing() {
    let error = parse("=1 2").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::UnexpectedToken);
}

/// Unary minus binds tighter than exponentiation.
#[test]
fn example_unary_before_power() {
    let expr = parse("=-2^2").expect("example parses");
    assert_eq!(
        expr.to_string(),
        "(binary power (unary negate (number 2)) (number 2))"
    );
}

/// The group never closes.
#[test]
fn example_unclosed_group() {
    let error = parse("=(1 + 2").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::UnexpectedEnd);
}

/// The input ends inside an expression.
#[test]
fn example_unexpected_end() {
    let error = parse("=1 +").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::UnexpectedEnd);
}

/// `AVG` is not in the registry.
#[test]
fn example_unknown_function() {
    let error = parse("=AVG(1, 2)").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::UnknownFunction);
}

/// The string never closes.
#[test]
fn example_unterminated() {
    let error = parse("=\"abc").expect_err("example fails to parse");
    assert_eq!(error.kind, ErrorKind::UnterminatedString);
}

/// Spaces and tabs between tokens are ignored, including at the end.
#[test]
fn example_whitespace() {
    let expr = parse("=  1+\t2 ").expect("example parses");
    assert_eq!(expr.to_string(), "(binary add (number 1) (number 2))");
}
